export const defaultPresets = {
  'modern-minimal': {
    label: 'Modern Minimal',
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#e0f2fe',
        'accent-foreground': '#1e3a8a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#3b82f6',
        'chart-1': '#3b82f6',
        'chart-2': '#2563eb',
        'chart-3': '#1d4ed8',
        'chart-4': '#1e40af',
        'chart-5': '#1e3a8a',
        radius: '0.375rem',
        sidebar: '#f9fafb',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#e0f2fe',
        'sidebar-accent-foreground': '#1e3a8a',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#3b82f6',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'JetBrains Mono, monospace',
      },
      dark: {
        background: '#171717',
        foreground: '#e5e5e5',
        card: '#262626',
        'card-foreground': '#e5e5e5',
        popover: '#262626',
        'popover-foreground': '#e5e5e5',
        primary: '#3b82f6',
        'primary-foreground': '#ffffff',
        secondary: '#262626',
        'secondary-foreground': '#e5e5e5',
        muted: '#262626',
        'muted-foreground': '#a3a3a3',
        accent: '#1e3a8a',
        'accent-foreground': '#bfdbfe',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#404040',
        input: '#404040',
        ring: '#3b82f6',
        'chart-1': '#60a5fa',
        'chart-2': '#3b82f6',
        'chart-3': '#2563eb',
        'chart-4': '#1d4ed8',
        'chart-5': '#1e40af',
        radius: '0.375rem',
        sidebar: '#171717',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#3b82f6',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#1e3a8a',
        'sidebar-accent-foreground': '#bfdbfe',
        'sidebar-border': '#404040',
        'sidebar-ring': '#3b82f6',
      },
    },
  },

  't3-chat': {
    label: 'T3 Chat',
    createdAt: '2025-04-19',
    styles: {
      light: {
        background: '#faf5fa',
        foreground: '#501854',
        card: '#faf5fa',
        'card-foreground': '#501854',
        popover: '#ffffff',
        'popover-foreground': '#501854',
        primary: '#a84370',
        'primary-foreground': '#ffffff',
        secondary: '#f1c4e6',
        'secondary-foreground': '#77347c',
        muted: '#f6e5f3',
        'muted-foreground': '#834588',
        accent: '#f1c4e6',
        'accent-foreground': '#77347c',
        destructive: '#ab4347',
        'destructive-foreground': '#ffffff',
        border: '#efbdeb',
        input: '#e7c1dc',
        ring: '#db2777',
        'chart-1': '#d926a2',
        'chart-2': '#6c12b9',
        'chart-3': '#274754',
        'chart-4': '#e8c468',
        'chart-5': '#f4a462',
        sidebar: '#f3e4f6',
        'sidebar-foreground': '#ac1668',
        'sidebar-primary': '#454554',
        'sidebar-primary-foreground': '#faf1f7',
        'sidebar-accent': '#f8f8f7',
        'sidebar-accent-foreground': '#454554',
        'sidebar-border': '#eceae9',
        'sidebar-ring': '#db2777',
        radius: '0.5rem',
      },
      dark: {
        background: '#221d27',
        foreground: '#d2c4de',
        card: '#2c2632',
        'card-foreground': '#dbc5d2',
        popover: '#100a0e',
        'popover-foreground': '#f8f1f5',
        primary: '#a3004c',
        'primary-foreground': '#efc0d8',
        secondary: '#362d3d',
        'secondary-foreground': '#d4c7e1',
        muted: '#28222d',
        'muted-foreground': '#c2b6cf',
        accent: '#463753',
        'accent-foreground': '#f8f1f5',
        destructive: '#ff0000',
        'destructive-foreground': '#ffffff',
        border: '#3b3237',
        input: '#3e343c',
        ring: '#db2777',
        'chart-1': '#a84370',
        'chart-2': '#934dcb',
        'chart-3': '#e88c30',
        'chart-4': '#af57db',
        'chart-5': '#e23670',
        sidebar: '#181117',
        'sidebar-foreground': '#e0cad6',
        'sidebar-primary': '#1d4ed8',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#261922',
        'sidebar-accent-foreground': '#f4f4f5',
        'sidebar-border': '#000000',
        'sidebar-ring': '#db2777',
        radius: '0.5rem',
      },
    },
  },

  'mocha-mousse': {
    label: 'Mocha Mousse',
    createdAt: '2025-04-24',
    styles: {
      light: {
        background: '#F1F0E5',
        foreground: '#56453F',
        card: '#F1F0E5',
        'card-foreground': '#56453F',
        popover: '#FFFFFF',
        'popover-foreground': '#56453F',
        primary: '#A37764',
        'primary-foreground': '#FFFFFF',
        secondary: '#BAAB92',
        'secondary-foreground': '#ffffff',
        muted: '#E4C7B8',
        'muted-foreground': '#8A655A',
        accent: '#E4C7B8',
        'accent-foreground': '#56453F',
        destructive: '#1f1a17',
        'destructive-foreground': '#FFFFFF',
        border: '#BAAB92',
        input: '#BAAB92',
        ring: '#A37764',
        'chart-1': '#A37764',
        'chart-2': '#8A655A',
        'chart-3': '#C39E88',
        'chart-4': '#BAAB92',
        'chart-5': '#A28777',
        sidebar: '#ebd6cb',
        'sidebar-foreground': '#56453F',
        'sidebar-primary': '#A37764',
        'sidebar-primary-foreground': '#FFFFFF',
        'sidebar-accent': '#C39E88',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#A28777',
        'sidebar-ring': '#A37764',
        'font-sans': 'DM Sans, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'Menlo, monospace',
        radius: '0.5rem',
        'shadow-color': 'hsl(20 18% 51% / 0.4)',
        'shadow-opacity': '0.11',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '2px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#2d2521',
        foreground: '#F1F0E5',
        card: '#3c332e',
        'card-foreground': '#F1F0E5',
        popover: '#3c332e',
        'popover-foreground': '#F1F0E5',
        primary: '#C39E88',
        'primary-foreground': '#2d2521',
        secondary: '#8A655A',
        'secondary-foreground': '#F1F0E5',
        muted: '#56453F',
        'muted-foreground': '#c5aa9b',
        accent: '#BAAB92',
        'accent-foreground': '#2d2521',
        destructive: '#E57373',
        'destructive-foreground': '#2d2521',
        border: '#56453F',
        input: '#56453F',
        ring: '#C39E88',
        'chart-1': '#C39E88',
        'chart-2': '#BAAB92',
        'chart-3': '#A37764',
        'chart-4': '#8A655A',
        'chart-5': '#A28777',
        sidebar: '#1f1a17',
        radius: '0.5rem',
        'sidebar-foreground': '#F1F0E5',
        'sidebar-primary': '#C39E88',
        'sidebar-primary-foreground': '#1f1a17',
        'sidebar-accent': '#BAAB92',
        'sidebar-accent-foreground': '#1f1a17',
        'sidebar-border': '#56453F',
        'sidebar-ring': '#C39E88',
        'shadow-color': 'hsl(20 18% 30% / 0.5)',
      },
    },
  },

  bubblegum: {
    label: 'Bubblegum',
    createdAt: '2025-04-18',
    styles: {
      light: {
        background: '#f6e6ee',
        foreground: '#5b5b5b',
        card: '#fdedc9',
        'card-foreground': '#5b5b5b',
        popover: '#ffffff',
        'popover-foreground': '#5b5b5b',
        primary: '#d04f99',
        'primary-foreground': '#ffffff',
        secondary: '#8acfd1',
        'secondary-foreground': '#333333',
        muted: '#b2e1eb',
        'muted-foreground': '#7a7a7a',
        accent: '#fbe2a7',
        'accent-foreground': '#333333',
        destructive: '#f96f70',
        'destructive-foreground': '#ffffff',
        border: '#d04f99',
        input: '#e4e4e4',
        ring: '#e670ab',
        'chart-1': '#e670ab',
        'chart-2': '#84d2e2',
        'chart-3': '#fbe2a7',
        'chart-4': '#f3a0ca',
        'chart-5': '#d7488e',
        sidebar: '#f8d8ea',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#ec4899',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f9a8d4',
        'sidebar-accent-foreground': '#333333',
        'sidebar-border': '#f3e8ff',
        'sidebar-ring': '#ec4899',
        'font-sans': 'Poppins, sans-serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'Fira Code, monospace',
        radius: '0.4rem',
        'shadow-color': 'hsl(325.78 58.18% 56.86% / 0.5)',
        'shadow-opacity': '1.0',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '3px',
        'shadow-offset-y': '3px',
      },
      dark: {
        background: '#12242e',
        foreground: '#f3e3ea',
        card: '#1c2e38',
        'card-foreground': '#f3e3ea',
        popover: '#1c2e38',
        'popover-foreground': '#f3e3ea',
        primary: '#fbe2a7',
        'primary-foreground': '#12242e',
        secondary: '#e4a2b1',
        'secondary-foreground': '#12242e',
        muted: '#24272b',
        'muted-foreground': '#e4a2b1',
        accent: '#c67b96',
        'accent-foreground': '#f3e3ea',
        destructive: '#e35ea4',
        'destructive-foreground': '#12242e',
        border: '#324859',
        input: '#20333d',
        ring: '#50afb6',
        'chart-1': '#50afb6',
        'chart-2': '#e4a2b1',
        'chart-3': '#c67b96',
        'chart-4': '#175c6c',
        'chart-5': '#24272b',
        sidebar: '#101f28',
        'sidebar-foreground': '#f3f4f6',
        'sidebar-primary': '#ec4899',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f9a8d4',
        'sidebar-accent-foreground': '#1f2937',
        'sidebar-border': '#374151',
        'sidebar-ring': '#ec4899',
        'font-sans': 'Poppins, sans-serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'Fira Code, monospace',
        'shadow-color': '#324859',
        radius: '0.4rem',
      },
    },
  },

  'amethyst-haze': {
    label: 'Amethyst Haze',
    createdAt: '2025-05-08',
    styles: {
      light: {
        background: '#f8f7fa',
        foreground: '#3d3c4f',
        card: '#ffffff',
        'card-foreground': '#3d3c4f',
        popover: '#ffffff',
        'popover-foreground': '#3d3c4f',
        primary: '#8a79ab',
        'primary-foreground': '#f8f7fa',
        secondary: '#dfd9ec',
        'secondary-foreground': '#3d3c4f',
        muted: '#dcd9e3',
        'muted-foreground': '#6b6880',
        accent: '#e6a5b8',
        'accent-foreground': '#4b2e36',
        destructive: '#d95c5c',
        'destructive-foreground': '#f8f7fa',
        border: '#cec9d9',
        input: '#eae7f0',
        ring: '#8a79ab',
        'chart-1': '#8a79ab',
        'chart-2': '#e6a5b8',
        'chart-3': '#77b8a1',
        'chart-4': '#f0c88d',
        'chart-5': '#a0bbe3',
        sidebar: '#f1eff5',
        'sidebar-foreground': '#3d3c4f',
        'sidebar-primary': '#8a79ab',
        'sidebar-primary-foreground': '#f8f7fa',
        'sidebar-accent': '#e6a5b8',
        'sidebar-accent-foreground': '#4b2e36',
        'sidebar-border': '#d7d2e0',
        'sidebar-ring': '#8a79ab',
        'font-sans': 'Geist, sans-serif',
        'font-serif': '"Lora", Georgia, serif',
        'font-mono': '"Fira Code", "Courier New", monospace',
        radius: '0.5rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.06',
        'shadow-blur': '5px',
        'shadow-spread': '1px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '2px',
        'letter-spacing': '0em',
        spacing: '0.25rem',
      },
      dark: {
        background: '#1a1823',
        foreground: '#e0ddef',
        card: '#232030',
        'card-foreground': '#e0ddef',
        popover: '#232030',
        'popover-foreground': '#e0ddef',
        primary: '#a995c9',
        'primary-foreground': '#1a1823',
        secondary: '#5a5370',
        'secondary-foreground': '#e0ddef',
        muted: '#242031',
        'muted-foreground': '#a09aad',
        accent: '#372e3f',
        'accent-foreground': '#f2b8c6',
        destructive: '#e57373',
        'destructive-foreground': '#1a1823',
        border: '#302c40',
        input: '#2a273a',
        ring: '#a995c9',
        'chart-1': '#a995c9',
        'chart-2': '#f2b8c6',
        'chart-3': '#77b8a1',
        'chart-4': '#f0c88d',
        'chart-5': '#a0bbe3',
        sidebar: '#16141e',
        'sidebar-foreground': '#e0ddef',
        'sidebar-primary': '#a995c9',
        'sidebar-primary-foreground': '#1a1823',
        'sidebar-accent': '#372e3f',
        'sidebar-accent-foreground': '#f2b8c6',
        'sidebar-border': '#2a273a',
        'sidebar-ring': '#a995c9',
        radius: '0.5rem',
      },
    },
  },

  notebook: {
    label: 'Notebook',
    createdAt: '2025-05-10',
    styles: {
      light: {
        background: '#f9f9f9',
        foreground: '#3a3a3a',
        card: '#ffffff',
        'card-foreground': '#3a3a3a',
        popover: '#ffffff',
        'popover-foreground': '#3a3a3a',
        primary: '#606060',
        'primary-foreground': '#f0f0f0',
        secondary: '#dedede',
        'secondary-foreground': '#3a3a3a',
        muted: '#e3e3e3',
        'muted-foreground': '#505050',
        accent: '#f3eac8',
        'accent-foreground': '#5d4037',
        destructive: '#c87a7a',
        'destructive-foreground': '#ffffff',
        border: '#747272',
        input: '#ffffff',
        ring: '#a0a0a0',
        'chart-1': '#333333',
        'chart-2': '#555555',
        'chart-3': '#777777',
        'chart-4': '#999999',
        'chart-5': '#bbbbbb',
        sidebar: '#f0f0f0',
        'sidebar-foreground': '#3a3a3a',
        'sidebar-primary': '#606060',
        'sidebar-primary-foreground': '#f0f0f0',
        'sidebar-accent': '#f3eac8',
        'sidebar-accent-foreground': '#5d4037',
        'sidebar-border': '#c0c0c0',
        'sidebar-ring': '#a0a0a0',
        'font-sans': 'Architects Daughter, sans-serif',
        'font-serif': '"Times New Roman", Times, serif',
        'font-mono': '"Courier New", Courier, monospace',
        radius: '0.625rem',
        'shadow-color': '#000000',
        'shadow-opacity': '0.03',
        'shadow-blur': '5px',
        'shadow-spread': '0px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '4px',
        'letter-spacing': '0.5px',
        spacing: '0.25rem',
      },
      dark: {
        background: '#2b2b2b',
        foreground: '#dcdcdc',
        card: '#333333',
        'card-foreground': '#dcdcdc',
        popover: '#333333',
        'popover-foreground': '#dcdcdc',
        primary: '#b0b0b0',
        'primary-foreground': '#2b2b2b',
        secondary: '#5a5a5a',
        'secondary-foreground': '#c0c0c0',
        muted: '#454545',
        'muted-foreground': '#a0a0a0',
        accent: '#e0e0e0',
        'accent-foreground': '#333333',
        destructive: '#d9afaf',
        'destructive-foreground': '#2b2b2b',
        border: '#4f4f4f',
        input: '#333333',
        ring: '#c0c0c0',
        'chart-1': '#efefef',
        'chart-2': '#d0d0d0',
        'chart-3': '#b0b0b0',
        'chart-4': '#909090',
        'chart-5': '#707070',
        sidebar: '#212121',
        'sidebar-foreground': '#dcdcdc',
        'sidebar-primary': '#b0b0b0',
        'sidebar-primary-foreground': '#212121',
        'sidebar-accent': '#e0e0e0',
        'sidebar-accent-foreground': '#333333',
        'sidebar-border': '#4f4f4f',
        'sidebar-ring': '#c0c0c0',
        'font-sans': 'Architects Daughter, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': '"Fira Code", "Courier New", monospace',
        radius: '0.625rem',
        'shadow-color': '#000000',
        'shadow-opacity': '0.03',
        'shadow-blur': '5px',
        'shadow-spread': '0px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '4px',
        'letter-spacing': '0.5px',
        spacing: '0.25rem',
      },
    },
  },

  'doom-64': {
    label: 'Doom 64',
    createdAt: '2025-04-28',
    styles: {
      light: {
        background: '#cccccc',
        foreground: '#1f1f1f',
        card: '#b0b0b0',
        'card-foreground': '#1f1f1f',
        popover: '#b0b0b0',
        'popover-foreground': '#1f1f1f',
        primary: '#b71c1c',
        'primary-foreground': '#ffffff',
        secondary: '#556b2f',
        'secondary-foreground': '#ffffff',
        muted: '#b8b8b8',
        'muted-foreground': '#4a4a4a',
        accent: '#4682b4',
        'accent-foreground': '#ffffff',
        destructive: '#ff6f00',
        'destructive-foreground': '#000000',
        border: '#505050',
        input: '#505050',
        ring: '#b71c1c',
        'chart-1': '#b71c1c',
        'chart-2': '#556b2f',
        'chart-3': '#4682b4',
        'chart-4': '#ff6f00',
        'chart-5': '#8d6e63',
        sidebar: '#b0b0b0',
        'sidebar-foreground': '#1f1f1f',
        'sidebar-primary': '#b71c1c',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#4682b4',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#505050',
        'sidebar-ring': '#b71c1c',
        'font-sans': '"Oxanium", sans-serif',
        'font-serif':
          'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
        'font-mono': '"Source Code Pro", monospace',
        radius: '0px',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.4',
        'shadow-blur': '4px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '0em',
        spacing: '0.25rem',
      },
      dark: {
        background: '#1a1a1a',
        foreground: '#e0e0e0',
        card: '#2a2a2a',
        'card-foreground': '#e0e0e0',
        popover: '#2a2a2a',
        'popover-foreground': '#e0e0e0',
        primary: '#e53935',
        'primary-foreground': '#ffffff',
        secondary: '#689f38',
        'secondary-foreground': '#000000',
        muted: '#252525',
        'muted-foreground': '#a0a0a0',
        accent: '#64b5f6',
        'accent-foreground': '#000000',
        destructive: '#ffa000',
        'destructive-foreground': '#000000',
        border: '#4a4a4a',
        input: '#4a4a4a',
        ring: '#e53935',
        'chart-1': '#e53935',
        'chart-2': '#689f38',
        'chart-3': '#64b5f6',
        'chart-4': '#ffa000',
        'chart-5': '#a1887f',
        sidebar: '#141414',
        'sidebar-foreground': '#e0e0e0',
        'sidebar-primary': '#e53935',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#64b5f6',
        'sidebar-accent-foreground': '#000000',
        'sidebar-border': '#4a4a4a',
        'sidebar-ring': '#e53935',
        'font-sans': '"Oxanium", sans-serif',
        'font-serif':
          'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
        'font-mono': '"Source Code Pro", monospace',
        radius: '0px',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.6',
        'shadow-blur': '5px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
        'letter-spacing': '0em',
        spacing: '0.25rem',
      },
    },
  },

  catppuccin: {
    label: 'Catppuccin',
    createdAt: '2025-04-18',
    styles: {
      light: {
        background: '#eff1f5',
        foreground: '#4c4f69',
        card: '#ffffff',
        'card-foreground': '#4c4f69',
        popover: '#ccd0da',
        'popover-foreground': '#4c4f69',
        primary: '#8839ef',
        'primary-foreground': '#ffffff',
        secondary: '#ccd0da',
        'secondary-foreground': '#4c4f69',
        muted: '#dce0e8',
        'muted-foreground': '#6c6f85',
        accent: '#04a5e5',
        'accent-foreground': '#ffffff',
        destructive: '#d20f39',
        'destructive-foreground': '#ffffff',
        border: '#bcc0cc',
        input: '#ccd0da',
        ring: '#8839ef',
        'chart-1': '#8839ef',
        'chart-2': '#04a5e5',
        'chart-3': '#40a02b',
        'chart-4': '#fe640b',
        'chart-5': '#dc8a78',
        sidebar: '#e6e9ef',
        'sidebar-foreground': '#4c4f69',
        'sidebar-primary': '#8839ef',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#04a5e5',
        'sidebar-accent-foreground': '#ffffff',
        'sidebar-border': '#bcc0cc',
        'sidebar-ring': '#8839ef',
        'font-sans': 'Montserrat, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'Fira Code, monospace',
        radius: '0.35rem',
        'shadow-color': 'hsl(240 30% 25%)',
        'shadow-opacity': '0.12',
        'shadow-blur': '6px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#181825',
        foreground: '#cdd6f4',
        card: '#1e1e2e',
        'card-foreground': '#cdd6f4',
        popover: '#45475a',
        'popover-foreground': '#cdd6f4',
        primary: '#cba6f7',
        'primary-foreground': '#1e1e2e',
        secondary: '#585b70',
        'secondary-foreground': '#cdd6f4',
        muted: '#292c3c',
        'muted-foreground': '#a6adc8',
        accent: '#89dceb',
        'accent-foreground': '#1e1e2e',
        destructive: '#f38ba8',
        'destructive-foreground': '#1e1e2e',
        border: '#313244',
        input: '#313244',
        ring: '#cba6f7',
        'chart-1': '#cba6f7',
        'chart-2': '#89dceb',
        'chart-3': '#a6e3a1',
        'chart-4': '#fab387',
        'chart-5': '#f5e0dc',
        sidebar: '#11111b',
        radius: '0.35rem',
        'sidebar-foreground': '#cdd6f4',
        'sidebar-primary': '#cba6f7',
        'sidebar-primary-foreground': '#1e1e2e',
        'sidebar-accent': '#89dceb',
        'sidebar-accent-foreground': '#1e1e2e',
        'sidebar-border': '#45475a',
        'sidebar-ring': '#cba6f7',
      },
    },
  },

  graphite: {
    label: 'Graphite',
    createdAt: '2025-04-17',
    styles: {
      light: {
        background: '#f0f0f0',
        foreground: '#333333',
        card: '#f5f5f5',
        'card-foreground': '#333333',
        popover: '#f5f5f5',
        'popover-foreground': '#333333',
        primary: '#606060',
        'primary-foreground': '#ffffff',
        secondary: '#e0e0e0',
        'secondary-foreground': '#333333',
        muted: '#d9d9d9',
        'muted-foreground': '#666666',
        accent: '#c0c0c0',
        'accent-foreground': '#333333',
        destructive: '#cc3333',
        'destructive-foreground': '#ffffff',
        border: '#d0d0d0',
        input: '#e0e0e0',
        ring: '#606060',
        'chart-1': '#606060',
        'chart-2': '#476666',
        'chart-3': '#909090',
        'chart-4': '#a8a8a8',
        'chart-5': '#c0c0c0',
        sidebar: '#eaeaea',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#606060',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#c0c0c0',
        'sidebar-accent-foreground': '#333333',
        'sidebar-border': '#d0d0d0',
        'sidebar-ring': '#606060',
        'font-sans': 'Montserrat, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'Fira Code, monospace',
        radius: '0.35rem',
        'shadow-color': 'hsl(0 0% 20% / 0.1)',
        'shadow-opacity': '0.15',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#1a1a1a',
        foreground: '#d9d9d9',
        card: '#202020',
        'card-foreground': '#d9d9d9',
        popover: '#202020',
        'popover-foreground': '#d9d9d9',
        primary: '#a0a0a0',
        'primary-foreground': '#1a1a1a',
        secondary: '#303030',
        'secondary-foreground': '#d9d9d9',
        muted: '#2a2a2a',
        'muted-foreground': '#808080',
        accent: '#404040',
        'accent-foreground': '#d9d9d9',
        destructive: '#e06666',
        'destructive-foreground': '#ffffff',
        border: '#353535',
        input: '#303030',
        ring: '#a0a0a0',
        'chart-1': '#a0a0a0',
        'chart-2': '#7e9ca0',
        'chart-3': '#707070',
        'chart-4': '#585858',
        'chart-5': '#404040',
        sidebar: '#1f1f1f',
        'sidebar-foreground': '#d9d9d9',
        'sidebar-primary': '#a0a0a0',
        'sidebar-primary-foreground': '#1a1a1a',
        'sidebar-accent': '#404040',
        'sidebar-accent-foreground': '#d9d9d9',
        'sidebar-border': '#353535',
        'sidebar-ring': '#a0a0a0',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'Fira Code, monospace',
        radius: '0.35rem',
      },
    },
  },

  'kodama-grove': {
    label: 'Kodama Grove',
    styles: {
      light: {
        background: '#e4d7b0',
        foreground: '#5c4b3e',
        card: '#e7dbbf',
        'card-foreground': '#5c4b3e',
        popover: '#f3ead2',
        'popover-foreground': '#5c4b3e',
        primary: '#8d9d4f',
        'primary-foreground': '#fdfbf6',
        secondary: '#decea0',
        'secondary-foreground': '#5c4b3e',
        muted: '#decea0',
        'muted-foreground': '#85766a',
        accent: '#dbc894',
        'accent-foreground': '#5c4b3e',
        destructive: '#d98b7e',
        'destructive-foreground': '#faf8f2',
        border: '#b19681',
        input: '#dbc894',
        ring: '#9db18c',
        'chart-1': '#9db18c',
        'chart-2': '#8a9f7b',
        'chart-3': '#bac9b4',
        'chart-4': '#71856a',
        'chart-5': '#5e6e58',
        sidebar: '#e2d1a2',
        'sidebar-foreground': '#5c4b3e',
        'sidebar-primary': '#9db18c',
        'sidebar-primary-foreground': '#fdfbf6',
        'sidebar-accent': '#eae5d9',
        'sidebar-accent-foreground': '#5c4b3e',
        'sidebar-border': '#e5e0d4',
        'sidebar-ring': '#9db18c',
        'font-sans': 'Merriweather, serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'JetBrains Mono, monospace',
        radius: '0.425rem',
        'shadow-color': 'hsl(88 22% 35% / 0.15)',
        'shadow-opacity': '0.15',
        'shadow-blur': '2px',
        'shadow-spread': '0px',
        'shadow-offset-x': '3px',
        'shadow-offset-y': '3px',
      },
      dark: {
        background: '#3a3529',
        foreground: '#ede4d4',
        card: '#413c33',
        'card-foreground': '#ede4d4',
        popover: '#413c33',
        'popover-foreground': '#ede4d4',
        primary: '#8a9f7b',
        'primary-foreground': '#2a2521',
        secondary: '#5a5345',
        'secondary-foreground': '#ede4d4',
        muted: '#4a4439',
        'muted-foreground': '#a8a096',
        accent: '#a18f5c',
        'accent-foreground': '#2a2521',
        destructive: '#b5766a',
        'destructive-foreground': '#f0e9db',
        border: '#5a5345',
        input: '#5a5345',
        ring: '#8a9f7b',
        'chart-1': '#8a9f7b',
        'chart-2': '#9db18c',
        'chart-3': '#71856a',
        'chart-4': '#a18f5c',
        'chart-5': '#5e6e58',
        sidebar: '#3a3529',
        'sidebar-foreground': '#ede4d4',
        'sidebar-primary': '#8a9f7b',
        'sidebar-primary-foreground': '#2a2521',
        'sidebar-accent': '#a18f5c',
        'sidebar-accent-foreground': '#2a2521',
        'sidebar-border': '#5a5345',
        'sidebar-ring': '#8a9f7b',
        radius: '0.425rem',
      },
    },
  },

  'cosmic-night': {
    label: 'Cosmic Night',
    createdAt: '2025-04-04',
    styles: {
      light: {
        background: '#f5f5ff',
        foreground: '#2a2a4a',
        card: '#ffffff',
        'card-foreground': '#2a2a4a',
        popover: '#ffffff',
        'popover-foreground': '#2a2a4a',
        primary: '#6e56cf',
        'primary-foreground': '#ffffff',
        secondary: '#e4dfff',
        'secondary-foreground': '#4a4080',
        muted: '#f0f0fa',
        'muted-foreground': '#6c6c8a',
        accent: '#d8e6ff',
        'accent-foreground': '#2a2a4a',
        destructive: '#ff5470',
        'destructive-foreground': '#ffffff',
        border: '#e0e0f0',
        input: '#e0e0f0',
        ring: '#6e56cf',
        'chart-1': '#6e56cf',
        'chart-2': '#9e8cfc',
        'chart-3': '#5d5fef',
        'chart-4': '#7c75fa',
        'chart-5': '#4740b3',
        radius: '0.5rem',
        sidebar: '#f0f0fa',
        'sidebar-foreground': '#2a2a4a',
        'sidebar-primary': '#6e56cf',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#d8e6ff',
        'sidebar-accent-foreground': '#2a2a4a',
        'sidebar-border': '#e0e0f0',
        'sidebar-ring': '#6e56cf',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Georgia, serif',
        'font-mono': 'JetBrains Mono, monospace',
        'shadow-color': 'hsl(240 30% 25%)',
        'shadow-opacity': '0.12',
        'shadow-blur': '10px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#0f0f1a',
        foreground: '#e2e2f5',
        card: '#1a1a2e',
        'card-foreground': '#e2e2f5',
        popover: '#1a1a2e',
        'popover-foreground': '#e2e2f5',
        primary: '#a48fff',
        'primary-foreground': '#0f0f1a',
        secondary: '#2d2b55',
        'secondary-foreground': '#c4c2ff',
        muted: '#222244',
        'muted-foreground': '#a0a0c0',
        accent: '#303060',
        'accent-foreground': '#e2e2f5',
        destructive: '#ff5470',
        'destructive-foreground': '#ffffff',
        border: '#303052',
        input: '#303052',
        ring: '#a48fff',
        'chart-1': '#a48fff',
        'chart-2': '#7986cb',
        'chart-3': '#64b5f6',
        'chart-4': '#4db6ac',
        'chart-5': '#ff79c6',
        radius: '0.5rem',
        sidebar: '#1a1a2e',
        'sidebar-foreground': '#e2e2f5',
        'sidebar-primary': '#a48fff',
        'sidebar-primary-foreground': '#0f0f1a',
        'sidebar-accent': '#303060',
        'sidebar-accent-foreground': '#e2e2f5',
        'sidebar-border': '#303052',
        'sidebar-ring': '#a48fff',
      },
    },
  },

  tangerine: {
    label: 'Tangerine',
    createdAt: '2025-04-09',
    styles: {
      light: {
        background: '#e8ebed',
        foreground: '#333333',
        card: '#ffffff',
        'card-foreground': '#333333',
        popover: '#ffffff',
        'popover-foreground': '#333333',
        primary: '#e05d38',
        'primary-foreground': '#ffffff',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#d6e4f0',
        'accent-foreground': '#1e3a8a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#dcdfe2',
        input: '#f4f5f7',
        ring: '#e05d38',
        'chart-1': '#86a7c8',
        'chart-2': '#eea591',
        'chart-3': '#5a7ca6',
        'chart-4': '#466494',
        'chart-5': '#334c82',
        sidebar: '#dddfe2',
        'sidebar-foreground': '#333333',
        'sidebar-primary': '#e05d38',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#d6e4f0',
        'sidebar-accent-foreground': '#1e3a8a',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#e05d38',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'JetBrains Mono, monospace',
        radius: '0.75rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '1px',
      },
      dark: {
        background: '#1c2433',
        foreground: '#e5e5e5',
        card: '#2a3040',
        'card-foreground': '#e5e5e5',
        popover: '#262b38',
        'popover-foreground': '#e5e5e5',
        primary: '#e05d38',
        'primary-foreground': '#ffffff',
        secondary: '#2a303e',
        'secondary-foreground': '#e5e5e5',
        muted: '#2a303e',
        'muted-foreground': '#a3a3a3',
        accent: '#2a3656',
        'accent-foreground': '#bfdbfe',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#3d4354',
        input: '#3d4354',
        ring: '#e05d38',
        'chart-1': '#86a7c8',
        'chart-2': '#e6a08f',
        'chart-3': '#5a7ca6',
        'chart-4': '#466494',
        'chart-5': '#334c82',
        sidebar: '#2a303f',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#e05d38',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#2a3656',
        'sidebar-accent-foreground': '#bfdbfe',
        'sidebar-border': '#3d4354',
        'sidebar-ring': '#e05d38',
        radius: '0.75rem',
      },
    },
  },

  nature: {
    label: 'Nature',
    styles: {
      light: {
        background: '#f8f5f0',
        foreground: '#3e2723',
        card: '#f8f5f0',
        'card-foreground': '#3e2723',
        popover: '#f8f5f0',
        'popover-foreground': '#3e2723',
        primary: '#2e7d32',
        'primary-foreground': '#ffffff',
        secondary: '#e8f5e9',
        'secondary-foreground': '#1b5e20',
        muted: '#f0e9e0',
        'muted-foreground': '#6d4c41',
        accent: '#c8e6c9',
        'accent-foreground': '#1b5e20',
        destructive: '#c62828',
        'destructive-foreground': '#ffffff',
        border: '#e0d6c9',
        input: '#e0d6c9',
        ring: '#2e7d32',
        'chart-1': '#4caf50',
        'chart-2': '#388e3c',
        'chart-3': '#2e7d32',
        'chart-4': '#1b5e20',
        'chart-5': '#0a1f0c',
        radius: '0.5rem',
        sidebar: '#f0e9e0',
        'sidebar-foreground': '#3e2723',
        'sidebar-primary': '#2e7d32',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#c8e6c9',
        'sidebar-accent-foreground': '#1b5e20',
        'sidebar-border': '#e0d6c9',
        'sidebar-ring': '#2e7d32',
        'font-sans': 'Montserrat, sans-serif',
        'font-serif': 'Merriweather, serif',
        'font-mono': 'Source Code Pro, monospace',
      },
      dark: {
        background: '#1c2a1f',
        foreground: '#f0ebe5',
        card: '#2d3a2e',
        'card-foreground': '#f0ebe5',
        popover: '#2d3a2e',
        'popover-foreground': '#f0ebe5',
        primary: '#4caf50',
        'primary-foreground': '#0a1f0c',
        secondary: '#3e4a3d',
        'secondary-foreground': '#d7e0d6',
        muted: '#2d3a2e',
        'muted-foreground': '#d7cfc4',
        accent: '#388e3c',
        'accent-foreground': '#f0ebe5',
        destructive: '#c62828',
        'destructive-foreground': '#f0ebe5',
        border: '#3e4a3d',
        input: '#3e4a3d',
        ring: '#4caf50',
        'chart-1': '#81c784',
        'chart-2': '#66bb6a',
        'chart-3': '#4caf50',
        'chart-4': '#43a047',
        'chart-5': '#388e3c',
        radius: '0.5rem',
        sidebar: '#1c2a1f',
        'sidebar-foreground': '#f0ebe5',
        'sidebar-primary': '#4caf50',
        'sidebar-primary-foreground': '#0a1f0c',
        'sidebar-accent': '#388e3c',
        'sidebar-accent-foreground': '#f0ebe5',
        'sidebar-border': '#3e4a3d',
        'sidebar-ring': '#4caf50',
      },
    },
  },

  'elegant-luxury': {
    label: 'Elegant Luxury',
    styles: {
      light: {
        background: '#faf7f5',
        foreground: '#1a1a1a',
        card: '#faf7f5',
        'card-foreground': '#1a1a1a',
        popover: '#faf7f5',
        'popover-foreground': '#1a1a1a',
        primary: '#9b2c2c',
        'primary-foreground': '#ffffff',
        secondary: '#fdf2d6',
        'secondary-foreground': '#805500',
        muted: '#f0ebe8',
        'muted-foreground': '#57534e',
        accent: '#fef3c7',
        'accent-foreground': '#7f1d1d',
        destructive: '#991b1b',
        'destructive-foreground': '#ffffff',
        border: '#f5e8d2',
        input: '#f5e8d2',
        ring: '#9b2c2c',
        'chart-1': '#b91c1c',
        'chart-2': '#9b2c2c',
        'chart-3': '#7f1d1d',
        'chart-4': '#b45309',
        'chart-5': '#92400e',
        radius: '0.375rem',
        sidebar: '#f0ebe8',
        'sidebar-foreground': '#1a1a1a',
        'sidebar-primary': '#9b2c2c',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fef3c7',
        'sidebar-accent-foreground': '#7f1d1d',
        'sidebar-border': '#f5e8d2',
        'sidebar-ring': '#9b2c2c',
        'font-sans': 'Poppins, sans-serif',
        'font-serif': 'Libre Baskerville, serif',
        'font-mono': 'IBM Plex Mono, monospace',
        'shadow-color': 'hsl(0 63% 18%)',
        'shadow-opacity': '0.12',
        'shadow-blur': '16px',
        'shadow-spread': '-2px',
        'shadow-offset-x': '1px',
        'shadow-offset-y': '1px',
      },
      dark: {
        background: '#1c1917',
        foreground: '#f5f5f4',
        card: '#292524',
        'card-foreground': '#f5f5f4',
        popover: '#292524',
        'popover-foreground': '#f5f5f4',
        primary: '#b91c1c',
        'primary-foreground': '#faf7f5',
        secondary: '#92400e',
        'secondary-foreground': '#fef3c7',
        muted: '#292524',
        'muted-foreground': '#d6d3d1',
        accent: '#b45309',
        'accent-foreground': '#fef3c7',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#44403c',
        input: '#44403c',
        ring: '#b91c1c',
        'chart-1': '#f87171',
        'chart-2': '#ef4444',
        'chart-3': '#dc2626',
        'chart-4': '#fbbf24',
        'chart-5': '#f59e0b',
        radius: '0.375rem',
        sidebar: '#1c1917',
        'sidebar-foreground': '#f5f5f4',
        'sidebar-primary': '#b91c1c',
        'sidebar-primary-foreground': '#faf7f5',
        'sidebar-accent': '#b45309',
        'sidebar-accent-foreground': '#fef3c7',
        'sidebar-border': '#44403c',
        'sidebar-ring': '#b91c1c',
      },
    },
  },

  'amber-minimal': {
    label: 'Amber Minimal',
    createdAt: '2025-04-27',
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#262626',
        card: '#ffffff',
        'card-foreground': '#262626',
        popover: '#ffffff',
        'popover-foreground': '#262626',
        primary: '#f59e0b',
        'primary-foreground': '#000000',
        secondary: '#f3f4f6',
        'secondary-foreground': '#4b5563',
        muted: '#f9fafb',
        'muted-foreground': '#6b7280',
        accent: '#fffbeb',
        'accent-foreground': '#92400e',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#f59e0b',
        'chart-1': '#f59e0b',
        'chart-2': '#d97706',
        'chart-3': '#b45309',
        'chart-4': '#92400e',
        'chart-5': '#78350f',
        sidebar: '#f9fafb',
        'sidebar-foreground': '#262626',
        'sidebar-primary': '#f59e0b',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#fffbeb',
        'sidebar-accent-foreground': '#92400e',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#f59e0b',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'JetBrains Mono, monospace',
        radius: '0.375rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '8px',
        'shadow-spread': '-1px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
        'letter-spacing': '0em',
        spacing: '0.25rem',
      },
      dark: {
        background: '#171717',
        foreground: '#e5e5e5',
        card: '#262626',
        'card-foreground': '#e5e5e5',
        popover: '#262626',
        'popover-foreground': '#e5e5e5',
        primary: '#f59e0b',
        'primary-foreground': '#000000',
        secondary: '#262626',
        'secondary-foreground': '#e5e5e5',
        muted: '#262626',
        'muted-foreground': '#a3a3a3',
        accent: '#92400e',
        'accent-foreground': '#fde68a',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#404040',
        input: '#404040',
        ring: '#f59e0b',
        'chart-1': '#fbbf24',
        'chart-2': '#d97706',
        'chart-3': '#92400e',
        'chart-4': '#b45309',
        'chart-5': '#92400e',
        sidebar: '#0f0f0f',
        'sidebar-foreground': '#e5e5e5',
        'sidebar-primary': '#f59e0b',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#92400e',
        'sidebar-accent-foreground': '#fde68a',
        'sidebar-border': '#404040',
        'sidebar-ring': '#f59e0b',
        radius: '0.375rem',
      },
    },
  },

  supabase: {
    label: 'Supabase',
    createdAt: '2025-04-27',
    styles: {
      light: {
        background: '#fcfcfc',
        foreground: '#171717',
        card: '#fcfcfc',
        'card-foreground': '#171717',
        popover: '#fcfcfc',
        'popover-foreground': '#525252',
        primary: '#72e3ad',
        'primary-foreground': '#1e2723',
        secondary: '#fdfdfd',
        'secondary-foreground': '#171717',
        muted: '#ededed',
        'muted-foreground': '#202020',
        accent: '#ededed',
        'accent-foreground': '#202020',
        destructive: '#ca3214',
        'destructive-foreground': '#fffcfc',
        border: '#dfdfdf',
        input: '#f6f6f6',
        ring: '#72e3ad',
        'chart-1': '#72e3ad',
        'chart-2': '#3b82f6',
        'chart-3': '#8b5cf6',
        'chart-4': '#f59e0b',
        'chart-5': '#10b981',
        sidebar: '#fcfcfc',
        'sidebar-foreground': '#707070',
        'sidebar-primary': '#72e3ad',
        'sidebar-primary-foreground': '#1e2723',
        'sidebar-accent': '#ededed',
        'sidebar-accent-foreground': '#202020',
        'sidebar-border': '#dfdfdf',
        'sidebar-ring': '#72e3ad',
        'font-sans': 'Outfit, sans-serif',
        'font-serif':
          'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
        'font-mono': 'monospace',
        radius: '0.5rem',
        'shadow-color': '#000000',
        'shadow-opacity': '0.17',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '1px',
        'letter-spacing': '0.025em',
      },
      dark: {
        background: '#121212',
        foreground: '#e2e8f0',
        card: '#171717',
        'card-foreground': '#e2e8f0',
        popover: '#242424',
        'popover-foreground': '#a9a9a9',
        primary: '#006239',
        'primary-foreground': '#dde8e3',
        secondary: '#242424',
        'secondary-foreground': '#fafafa',
        muted: '#1f1f1f',
        'muted-foreground': '#a2a2a2',
        accent: '#313131',
        'accent-foreground': '#fafafa',
        destructive: '#541c15',
        'destructive-foreground': '#ede9e8',
        border: '#292929',
        input: '#242424',
        ring: '#4ade80',
        'chart-1': '#4ade80',
        'chart-2': '#60a5fa',
        'chart-3': '#a78bfa',
        'chart-4': '#fbbf24',
        'chart-5': '#2dd4bf',
        sidebar: '#121212',
        'sidebar-foreground': '#898989',
        'sidebar-primary': '#006239',
        'sidebar-primary-foreground': '#dde8e3',
        'sidebar-accent': '#313131',
        'sidebar-accent-foreground': '#fafafa',
        'sidebar-border': '#292929',
        'sidebar-ring': '#4ade80',
        radius: '0.5rem',
      },
    },
  },

  'solar-dusk': {
    label: 'Solar Dusk',
    createdAt: '2025-04-12',
    styles: {
      light: {
        background: '#FDFBF7',
        foreground: '#4A3B33',
        card: '#F8F4EE',
        'card-foreground': '#4A3B33',
        popover: '#F8F4EE',
        'popover-foreground': '#4A3B33',
        primary: '#B45309',
        'primary-foreground': '#FFFFFF',
        secondary: '#E4C090',
        'secondary-foreground': '#57534E',
        muted: '#F1E9DA',
        'muted-foreground': '#78716C',
        accent: '#f2daba',
        'accent-foreground': '#57534E',
        destructive: '#991B1B',
        'destructive-foreground': '#FFFFFF',
        border: '#E4D9BC',
        input: '#E4D9BC',
        ring: '#B45309',
        'chart-1': '#B45309',
        'chart-2': '#78716C',
        'chart-3': '#A16207',
        'chart-4': '#78716C',
        'chart-5': '#CA8A04',
        radius: '0.3rem',
        sidebar: '#F1E9DA',
        'sidebar-foreground': '#4A3B33',
        'sidebar-primary': '#B45309',
        'sidebar-primary-foreground': '#FFFFFF',
        'sidebar-accent': '#A16207',
        'sidebar-accent-foreground': '#FFFFFF',
        'sidebar-border': '#E4D9BC',
        'sidebar-ring': '#B45309',
        'font-sans': 'Oxanium, sans-serif',
        'font-serif': 'Merriweather, serif',
        'font-mono': 'Fira Code, monospace',
        'shadow-color': 'hsl(28 18% 25%)',
        'shadow-opacity': '0.18',
        'shadow-blur': '3px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#1C1917',
        foreground: '#F5F5F4',
        card: '#292524',
        'card-foreground': '#F5F5F4',
        popover: '#292524',
        'popover-foreground': '#F5F5F4',
        primary: '#F97316',
        'primary-foreground': '#FFFFFF',
        secondary: '#57534E',
        'secondary-foreground': '#E7E5E4',
        muted: '#292524',
        'muted-foreground': '#A8A29E',
        accent: '#1e4252',
        'accent-foreground': '#E7E5E4',
        destructive: '#DC2626',
        'destructive-foreground': '#FFFFFF',
        border: '#44403C',
        input: '#44403C',
        ring: '#F97316',
        'chart-1': '#F97316',
        'chart-2': '#0EA5E9',
        'chart-3': '#EAB308',
        'chart-4': '#A8A29E',
        'chart-5': '#78716C',
        radius: '0.3rem',
        sidebar: '#292524',
        'sidebar-foreground': '#F5F5F4',
        'sidebar-primary': '#F97316',
        'sidebar-primary-foreground': '#FFFFFF',
        'sidebar-accent': '#0EA5E9',
        'sidebar-accent-foreground': '#0C2A4D',
        'sidebar-border': '#44403C',
        'sidebar-ring': '#F97316',
        'shadow-color': 'hsl(0 0% 5%)',
      },
    },
  },

  claymorphism: {
    label: 'Claymorphism',
    styles: {
      light: {
        background: '#e7e5e4',
        foreground: '#1e293b',
        card: '#f5f5f4',
        'card-foreground': '#1e293b',
        popover: '#f5f5f4',
        'popover-foreground': '#1e293b',
        primary: '#6366f1',
        'primary-foreground': '#ffffff',
        secondary: '#d6d3d1',
        'secondary-foreground': '#4b5563',
        muted: '#e7e5e4',
        'muted-foreground': '#6b7280',
        accent: '#f3e5f5',
        'accent-foreground': '#374151',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#d6d3d1',
        input: '#d6d3d1',
        ring: '#6366f1',
        'chart-1': '#6366f1',
        'chart-2': '#4f46e5',
        'chart-3': '#4338ca',
        'chart-4': '#3730a3',
        'chart-5': '#312e81',
        radius: '1.25rem',
        sidebar: '#d6d3d1',
        'sidebar-foreground': '#1e293b',
        'sidebar-primary': '#6366f1',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f3e5f5',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#d6d3d1',
        'sidebar-ring': '#6366f1',
        'font-sans': 'Plus Jakarta Sans, sans-serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'Roboto Mono, monospace',
        'shadow-color': 'hsl(240 4% 60%)',
        'shadow-opacity': '0.18',
        'shadow-blur': '10px',
        'shadow-spread': '4px',
        'shadow-offset-x': '2px',
        'shadow-offset-y': '2px',
      },
      dark: {
        background: '#1e1b18',
        foreground: '#e2e8f0',
        card: '#2c2825',
        'card-foreground': '#e2e8f0',
        popover: '#2c2825',
        'popover-foreground': '#e2e8f0',
        primary: '#818cf8',
        'primary-foreground': '#1e1b18',
        secondary: '#3a3633',
        'secondary-foreground': '#d1d5db',
        muted: '#2c2825',
        'muted-foreground': '#9ca3af',
        accent: '#484441',
        'accent-foreground': '#d1d5db',
        destructive: '#ef4444',
        'destructive-foreground': '#1e1b18',
        border: '#3a3633',
        input: '#3a3633',
        ring: '#818cf8',
        'chart-1': '#818cf8',
        'chart-2': '#6366f1',
        'chart-3': '#4f46e5',
        'chart-4': '#4338ca',
        'chart-5': '#3730a3',
        radius: '1.25rem',
        sidebar: '#3a3633',
        'sidebar-foreground': '#e2e8f0',
        'sidebar-primary': '#818cf8',
        'sidebar-primary-foreground': '#1e1b18',
        'sidebar-accent': '#484441',
        'sidebar-accent-foreground': '#d1d5db',
        'sidebar-border': '#3a3633',
        'sidebar-ring': '#818cf8',
        'shadow-color': 'hsl(0 0% 0%)',
      },
    },
  },

  cyberpunk: {
    label: 'Cyberpunk',
    styles: {
      light: {
        background: '#f8f9fa',
        foreground: '#0c0c1d',
        card: '#ffffff',
        'card-foreground': '#0c0c1d',
        popover: '#ffffff',
        'popover-foreground': '#0c0c1d',
        primary: '#ff00c8',
        'primary-foreground': '#ffffff',
        secondary: '#f0f0ff',
        'secondary-foreground': '#0c0c1d',
        muted: '#f0f0ff',
        'muted-foreground': '#0c0c1d',
        accent: '#00ffcc',
        'accent-foreground': '#0c0c1d',
        destructive: '#ff3d00',
        'destructive-foreground': '#ffffff',
        border: '#dfe6e9',
        input: '#dfe6e9',
        ring: '#ff00c8',
        'chart-1': '#ff00c8',
        'chart-2': '#9000ff',
        'chart-3': '#00e5ff',
        'chart-4': '#00ffcc',
        'chart-5': '#ffe600',
        radius: '0.5rem',
        sidebar: '#f0f0ff',
        'sidebar-foreground': '#0c0c1d',
        'sidebar-primary': '#ff00c8',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#00ffcc',
        'sidebar-accent-foreground': '#0c0c1d',
        'sidebar-border': '#dfe6e9',
        'sidebar-ring': '#ff00c8',
        'font-sans': 'Outfit, sans-serif',
        'font-mono': 'Fira Code, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '8px',
        'shadow-spread': '-2px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#0c0c1d',
        foreground: '#eceff4',
        card: '#1e1e3f',
        'card-foreground': '#eceff4',
        popover: '#1e1e3f',
        'popover-foreground': '#eceff4',
        primary: '#ff00c8',
        'primary-foreground': '#ffffff',
        secondary: '#1e1e3f',
        'secondary-foreground': '#eceff4',
        muted: '#1e1e3f',
        'muted-foreground': '#8085a6',
        accent: '#00ffcc',
        'accent-foreground': '#0c0c1d',
        destructive: '#ff3d00',
        'destructive-foreground': '#ffffff',
        border: '#2e2e5e',
        input: '#2e2e5e',
        ring: '#ff00c8',
        'chart-1': '#ff00c8',
        'chart-2': '#9000ff',
        'chart-3': '#00e5ff',
        'chart-4': '#00ffcc',
        'chart-5': '#ffe600',
        radius: '0.5rem',
        sidebar: '#0c0c1d',
        'sidebar-foreground': '#eceff4',
        'sidebar-primary': '#ff00c8',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#00ffcc',
        'sidebar-accent-foreground': '#0c0c1d',
        'sidebar-border': '#2e2e5e',
        'sidebar-ring': '#ff00c8',
      },
    },
  },
  'pastel-dreams': {
    label: 'Pastel Dreams',
    styles: {
      light: {
        background: '#f7f3f9',
        foreground: '#374151',
        card: '#ffffff',
        'card-foreground': '#374151',
        popover: '#ffffff',
        'popover-foreground': '#374151',
        primary: '#a78bfa',
        'primary-foreground': '#ffffff',
        secondary: '#e9d8fd',
        'secondary-foreground': '#4b5563',
        muted: '#f3e8ff',
        'muted-foreground': '#6b7280',
        accent: '#f3e5f5',
        'accent-foreground': '#374151',
        destructive: '#fca5a5',
        'destructive-foreground': '#ffffff',
        border: '#e9d8fd',
        input: '#e9d8fd',
        ring: '#a78bfa',
        'chart-1': '#a78bfa',
        'chart-2': '#8b5cf6',
        'chart-3': '#7c3aed',
        'chart-4': '#6d28d9',
        'chart-5': '#5b21b6',
        radius: '1.5rem',
        sidebar: '#e9d8fd',
        'sidebar-foreground': '#374151',
        'sidebar-primary': '#a78bfa',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#f3e5f5',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#e9d8fd',
        'sidebar-ring': '#a78bfa',
        'font-sans': 'Open Sans, sans-serif',
        'font-serif': 'Source Serif 4, serif',
        'font-mono': 'IBM Plex Mono, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.08',
        'shadow-blur': '16px',
        'shadow-spread': '-4px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '8px',
      },
      dark: {
        background: '#1c1917',
        foreground: '#e0e7ff',
        card: '#2d2535',
        'card-foreground': '#e0e7ff',
        popover: '#2d2535',
        'popover-foreground': '#e0e7ff',
        primary: '#c0aafd',
        'primary-foreground': '#1c1917',
        secondary: '#3f324a',
        'secondary-foreground': '#d1d5db',
        muted: '#2d2535',
        'muted-foreground': '#9ca3af',
        accent: '#4a3d5a',
        'accent-foreground': '#d1d5db',
        destructive: '#fca5a5',
        'destructive-foreground': '#1c1917',
        border: '#3f324a',
        input: '#3f324a',
        ring: '#c0aafd',
        'chart-1': '#c0aafd',
        'chart-2': '#a78bfa',
        'chart-3': '#8b5cf6',
        'chart-4': '#7c3aed',
        'chart-5': '#6d28d9',
        radius: '1.5rem',
        sidebar: '#3f324a',
        'sidebar-foreground': '#e0e7ff',
        'sidebar-primary': '#c0aafd',
        'sidebar-primary-foreground': '#1c1917',
        'sidebar-accent': '#4a3d5a',
        'sidebar-accent-foreground': '#d1d5db',
        'sidebar-border': '#3f324a',
        'sidebar-ring': '#c0aafd',
      },
    },
  },

  'clean-slate': {
    label: 'Clean Slate',
    styles: {
      light: {
        background: '#f8fafc',
        foreground: '#1e293b',
        card: '#ffffff',
        'card-foreground': '#1e293b',
        popover: '#ffffff',
        'popover-foreground': '#1e293b',
        primary: '#6366f1',
        'primary-foreground': '#ffffff',
        secondary: '#e5e7eb',
        'secondary-foreground': '#374151',
        muted: '#f3f4f6',
        'muted-foreground': '#6b7280',
        accent: '#e0e7ff',
        'accent-foreground': '#374151',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#d1d5db',
        input: '#d1d5db',
        ring: '#6366f1',
        'chart-1': '#6366f1',
        'chart-2': '#4f46e5',
        'chart-3': '#4338ca',
        'chart-4': '#3730a3',
        'chart-5': '#312e81',
        radius: '0.5rem',
        sidebar: '#f3f4f6',
        'sidebar-foreground': '#1e293b',
        'sidebar-primary': '#6366f1',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#e0e7ff',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#d1d5db',
        'sidebar-ring': '#6366f1',
        'font-sans': 'Inter, sans-serif',
        'font-serif': 'Merriweather, serif',
        'font-mono': 'JetBrains Mono, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '8px',
        'shadow-spread': '-1px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#0f172a',
        foreground: '#e2e8f0',
        card: '#1e293b',
        'card-foreground': '#e2e8f0',
        popover: '#1e293b',
        'popover-foreground': '#e2e8f0',
        primary: '#818cf8',
        'primary-foreground': '#0f172a',
        secondary: '#2d3748',
        'secondary-foreground': '#d1d5db',
        muted: '#1e293b',
        'muted-foreground': '#9ca3af',
        accent: '#374151',
        'accent-foreground': '#d1d5db',
        destructive: '#ef4444',
        'destructive-foreground': '#0f172a',
        border: '#4b5563',
        input: '#4b5563',
        ring: '#818cf8',
        'chart-1': '#818cf8',
        'chart-2': '#6366f1',
        'chart-3': '#4f46e5',
        'chart-4': '#4338ca',
        'chart-5': '#3730a3',
        radius: '0.5rem',
        sidebar: '#1e293b',
        'sidebar-foreground': '#e2e8f0',
        'sidebar-primary': '#818cf8',
        'sidebar-primary-foreground': '#0f172a',
        'sidebar-accent': '#374151',
        'sidebar-accent-foreground': '#d1d5db',
        'sidebar-border': '#4b5563',
        'sidebar-ring': '#818cf8',
      },
    },
  },

  caffeine: {
    label: 'Caffeine',
    styles: {
      light: {
        background: '#f9f9f9',
        foreground: '#202020',
        card: '#fcfcfc',
        'card-foreground': '#202020',
        popover: '#fcfcfc',
        'popover-foreground': '#202020',
        primary: '#644a40',
        'primary-foreground': '#ffffff',
        secondary: '#ffdfb5',
        'secondary-foreground': '#582d1d',
        muted: '#efefef',
        'muted-foreground': '#646464',
        accent: '#e8e8e8',
        'accent-foreground': '#202020',
        destructive: '#e54d2e',
        'destructive-foreground': '#ffffff',
        border: '#d8d8d8',
        input: '#d8d8d8',
        ring: '#644a40',
        'chart-1': '#644a40',
        'chart-2': '#ffdfb5',
        'chart-3': '#e8e8e8',
        'chart-4': '#ffe6c4',
        'chart-5': '#66493e',
        sidebar: '#fbfbfb',
        'sidebar-foreground': '#252525',
        'sidebar-primary': '#343434',
        'sidebar-primary-foreground': '#fbfbfb',
        'sidebar-accent': '#f7f7f7',
        'sidebar-accent-foreground': '#343434',
        'sidebar-border': '#ebebeb',
        'sidebar-ring': '#b5b5b5',
        radius: '0.5rem',
      },
      dark: {
        background: '#111111',
        foreground: '#eeeeee',
        card: '#191919',
        'card-foreground': '#eeeeee',
        popover: '#191919',
        'popover-foreground': '#eeeeee',
        primary: '#ffe0c2',
        'primary-foreground': '#081a1b',
        secondary: '#393028',
        'secondary-foreground': '#ffe0c2',
        muted: '#222222',
        'muted-foreground': '#b4b4b4',
        accent: '#2a2a2a',
        'accent-foreground': '#eeeeee',
        destructive: '#e54d2e',
        'destructive-foreground': '#ffffff',
        border: '#201e18',
        input: '#484848',
        ring: '#ffe0c2',
        'chart-1': '#ffe0c2',
        'chart-2': '#393028',
        'chart-3': '#2a2a2a',
        'chart-4': '#42382e',
        'chart-5': '#ffe0c1',
        sidebar: '#18181b',
        'sidebar-foreground': '#f4f4f5',
        'sidebar-primary': '#1d4ed8',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#27272a',
        'sidebar-accent-foreground': '#f4f4f5',
        'sidebar-border': '#27272a',
        'sidebar-ring': '#d4d4d8',
        radius: '0.5rem',
      },
    },
  },
  'ocean-breeze': {
    label: 'Ocean Breeze',
    styles: {
      light: {
        background: '#f0f8ff',
        foreground: '#374151',
        card: '#ffffff',
        'card-foreground': '#374151',
        popover: '#ffffff',
        'popover-foreground': '#374151',
        primary: '#22c55e',
        'primary-foreground': '#ffffff',
        secondary: '#e0f2fe',
        'secondary-foreground': '#4b5563',
        muted: '#f3f4f6',
        'muted-foreground': '#6b7280',
        accent: '#d1fae5',
        'accent-foreground': '#374151',
        destructive: '#ef4444',
        'destructive-foreground': '#ffffff',
        border: '#e5e7eb',
        input: '#e5e7eb',
        ring: '#22c55e',
        'chart-1': '#22c55e',
        'chart-2': '#10b981',
        'chart-3': '#059669',
        'chart-4': '#047857',
        'chart-5': '#065f46',
        radius: '0.5rem',
        sidebar: '#e0f2fe',
        'sidebar-foreground': '#374151',
        'sidebar-primary': '#22c55e',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#d1fae5',
        'sidebar-accent-foreground': '#374151',
        'sidebar-border': '#e5e7eb',
        'sidebar-ring': '#22c55e',
        'font-sans': 'DM Sans, sans-serif',
        'font-serif': 'Lora, serif',
        'font-mono': 'IBM Plex Mono, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.1',
        'shadow-blur': '8px',
        'shadow-spread': '-1px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '4px',
      },
      dark: {
        background: '#0f172a',
        foreground: '#d1d5db',
        card: '#1e293b',
        'card-foreground': '#d1d5db',
        popover: '#1e293b',
        'popover-foreground': '#d1d5db',
        primary: '#34d399',
        'primary-foreground': '#0f172a',
        secondary: '#2d3748',
        'secondary-foreground': '#a1a1aa',
        muted: '#1e293b',
        'muted-foreground': '#6b7280',
        accent: '#374151',
        'accent-foreground': '#a1a1aa',
        destructive: '#ef4444',
        'destructive-foreground': '#0f172a',
        border: '#4b5563',
        input: '#4b5563',
        ring: '#34d399',
        'chart-1': '#34d399',
        'chart-2': '#2dd4bf',
        'chart-3': '#22c55e',
        'chart-4': '#10b981',
        'chart-5': '#059669',
        radius: '0.5rem',
        sidebar: '#1e293b',
        'sidebar-foreground': '#d1d5db',
        'sidebar-primary': '#34d399',
        'sidebar-primary-foreground': '#0f172a',
        'sidebar-accent': '#374151',
        'sidebar-accent-foreground': '#a1a1aa',
        'sidebar-border': '#4b5563',
        'sidebar-ring': '#34d399',
      },
    },
  },

  'sunset-horizon': {
    label: 'Sunset Horizon',
    styles: {
      light: {
        background: '#fff9f5',
        foreground: '#3d3436',
        card: '#ffffff',
        'card-foreground': '#3d3436',
        popover: '#ffffff',
        'popover-foreground': '#3d3436',
        primary: '#ff7e5f',
        'primary-foreground': '#ffffff',
        secondary: '#ffedea',
        'secondary-foreground': '#b35340',
        muted: '#fff0eb',
        'muted-foreground': '#78716C',
        accent: '#feb47b',
        'accent-foreground': '#3d3436',
        destructive: '#e63946',
        'destructive-foreground': '#ffffff',
        border: '#ffe0d6',
        input: '#ffe0d6',
        ring: '#ff7e5f',
        'chart-1': '#ff7e5f',
        'chart-2': '#feb47b',
        'chart-3': '#ffcaa7',
        'chart-4': '#ffad8f',
        'chart-5': '#ce6a57',
        radius: '0.625rem',
        sidebar: '#fff0eb',
        'sidebar-foreground': '#3d3436',
        'sidebar-primary': '#ff7e5f',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#feb47b',
        'sidebar-accent-foreground': '#3d3436',
        'sidebar-border': '#ffe0d6',
        'sidebar-ring': '#ff7e5f',
        'font-sans': 'Montserrat, sans-serif',
        'font-serif': 'Merriweather, serif',
        'font-mono': 'Ubuntu Mono, monospace',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0.09',
        'shadow-blur': '12px',
        'shadow-spread': '-3px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '6px',
      },
      dark: {
        background: '#2a2024',
        foreground: '#f2e9e4',
        card: '#392f35',
        'card-foreground': '#f2e9e4',
        popover: '#392f35',
        'popover-foreground': '#f2e9e4',
        primary: '#ff7e5f',
        'primary-foreground': '#ffffff',
        secondary: '#463a41',
        'secondary-foreground': '#f2e9e4',
        muted: '#392f35',
        'muted-foreground': '#d7c6bc',
        accent: '#feb47b',
        'accent-foreground': '#2a2024',
        destructive: '#e63946',
        'destructive-foreground': '#ffffff',
        border: '#463a41',
        input: '#463a41',
        ring: '#ff7e5f',
        'chart-1': '#ff7e5f',
        'chart-2': '#feb47b',
        'chart-3': '#ffcaa7',
        'chart-4': '#ffad8f',
        'chart-5': '#ce6a57',
        radius: '0.625rem',
        sidebar: '#2a2024',
        'sidebar-foreground': '#f2e9e4',
        'sidebar-primary': '#ff7e5f',
        'sidebar-primary-foreground': '#ffffff',
        'sidebar-accent': '#feb47b',
        'sidebar-accent-foreground': '#2a2024',
        'sidebar-border': '#463a41',
        'sidebar-ring': '#ff7e5f',
      },
    },
  },

  mono: {
    label: 'Mono',
    createdAt: '2025-04-20',
    styles: {
      light: {
        background: '#ffffff',
        foreground: '#0a0a0a',
        card: '#ffffff',
        'card-foreground': '#0a0a0a',
        popover: '#ffffff',
        'popover-foreground': '#0a0a0a',
        primary: '#737373',
        'primary-foreground': '#fafafa',
        secondary: '#f5f5f5',
        'secondary-foreground': '#171717',
        muted: '#f5f5f5',
        'muted-foreground': '#717171',
        accent: '#f5f5f5',
        'accent-foreground': '#171717',
        destructive: '#e7000b',
        'destructive-foreground': '#f5f5f5',
        border: '#e5e5e5',
        input: '#e5e5e5',
        ring: '#a1a1a1',
        'chart-1': '#737373',
        'chart-2': '#737373',
        'chart-3': '#737373',
        'chart-4': '#737373',
        'chart-5': '#737373',
        sidebar: '#fafafa',
        'sidebar-foreground': '#0a0a0a',
        'sidebar-primary': '#171717',
        'sidebar-primary-foreground': '#fafafa',
        'sidebar-accent': '#f5f5f5',
        'sidebar-accent-foreground': '#171717',
        'sidebar-border': '#e5e5e5',
        'sidebar-ring': '#a1a1a1',
        'font-sans': 'Geist Mono, monospace',
        'font-serif': 'Geist Mono, monospace',
        'font-mono': 'Geist Mono, monospace',
        radius: '0rem',
        'shadow-color': 'hsl(0 0% 0%)',
        'shadow-opacity': '0',
        'shadow-blur': '0px',
        'shadow-spread': '0px',
        'shadow-offset-x': '0px',
        'shadow-offset-y': '1px',
      },
      dark: {
        background: '#0a0a0a',
        foreground: '#fafafa',
        card: '#191919',
        'card-foreground': '#fafafa',
        popover: '#262626',
        'popover-foreground': '#fafafa',
        primary: '#737373',
        'primary-foreground': '#fafafa',
        secondary: '#262626',
        'secondary-foreground': '#fafafa',
        muted: '#262626',
        'muted-foreground': '#a1a1a1',
        accent: '#404040',
        'accent-foreground': '#fafafa',
        destructive: '#ff6467',
        'destructive-foreground': '#262626',
        border: '#383838',
        input: '#525252',
        ring: '#737373',
        'chart-1': '#737373',
        'chart-2': '#737373',
        'chart-3': '#737373',
        'chart-4': '#737373',
        'chart-5': '#737373',
        sidebar: '#171717',
        'sidebar-foreground': '#fafafa',
        'sidebar-primary': '#fafafa',
        'sidebar-primary-foreground': '#171717',
        'sidebar-accent': '#262626',
        'sidebar-accent-foreground': '#fafafa',
        'sidebar-border': '#ffffff',
        'sidebar-ring': '#525252',
        radius: '0px',
      },
    },
  },
} as const;

export const presetsArray = Object.values(defaultPresets);
export type Preset = keyof typeof defaultPresets;
export type Theme = 'light' | 'dark';
export const presetKey = 'preset';
export const themeKey = 'theme';
export const defaults = {
  theme: 'light' as Theme,
  preset: 'mono' as Preset,
};
