/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as OrderIndexRouteImport } from './routes/order.index'
import { Route as LayoutIndexRouteImport } from './routes/_layout.index'
import { Route as AuthIdRouteImport } from './routes/auth.$id'
import { Route as LayoutCollectionRouteImport } from './routes/_layout.$collection'
import { Route as LayoutOrderHistoryIndexRouteImport } from './routes/_layout.order-history.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LayoutProductsCategorySlugIndexRouteImport } from './routes/_layout.products.$categorySlug.index'
import { Route as LayoutProductsCategorySlugSubcategorySlugIndexRouteImport } from './routes/_layout.products.$categorySlug.$subcategorySlug.index'
import { Route as LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRouteImport } from './routes/_layout.products.$categorySlug.$subcategorySlug.$productSlug.index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const AuthIdRoute = AuthIdRouteImport.update({
  id: '/auth/$id',
  path: '/auth/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutCollectionRoute = LayoutCollectionRouteImport.update({
  id: '/$collection',
  path: '/$collection',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrderHistoryIndexRoute = LayoutOrderHistoryIndexRouteImport.update({
  id: '/order-history/',
  path: '/order-history/',
  getParentRoute: () => LayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutProductsCategorySlugIndexRoute =
  LayoutProductsCategorySlugIndexRouteImport.update({
    id: '/products/$categorySlug/',
    path: '/products/$categorySlug/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProductsCategorySlugSubcategorySlugIndexRoute =
  LayoutProductsCategorySlugSubcategorySlugIndexRouteImport.update({
    id: '/products/$categorySlug/$subcategorySlug/',
    path: '/products/$categorySlug/$subcategorySlug/',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRoute =
  LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRouteImport.update({
    id: '/products/$categorySlug/$subcategorySlug/$productSlug/',
    path: '/products/$categorySlug/$subcategorySlug/$productSlug/',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$collection': typeof LayoutCollectionRoute
  '/auth/$id': typeof AuthIdRoute
  '/': typeof LayoutIndexRoute
  '/order': typeof OrderIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/order-history': typeof LayoutOrderHistoryIndexRoute
  '/products/$categorySlug': typeof LayoutProductsCategorySlugIndexRoute
  '/products/$categorySlug/$subcategorySlug': typeof LayoutProductsCategorySlugSubcategorySlugIndexRoute
  '/products/$categorySlug/$subcategorySlug/$productSlug': typeof LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRoute
}
export interface FileRoutesByTo {
  '/$collection': typeof LayoutCollectionRoute
  '/auth/$id': typeof AuthIdRoute
  '/': typeof LayoutIndexRoute
  '/order': typeof OrderIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/order-history': typeof LayoutOrderHistoryIndexRoute
  '/products/$categorySlug': typeof LayoutProductsCategorySlugIndexRoute
  '/products/$categorySlug/$subcategorySlug': typeof LayoutProductsCategorySlugSubcategorySlugIndexRoute
  '/products/$categorySlug/$subcategorySlug/$productSlug': typeof LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/$collection': typeof LayoutCollectionRoute
  '/auth/$id': typeof AuthIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/order/': typeof OrderIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_layout/order-history/': typeof LayoutOrderHistoryIndexRoute
  '/_layout/products/$categorySlug/': typeof LayoutProductsCategorySlugIndexRoute
  '/_layout/products/$categorySlug/$subcategorySlug/': typeof LayoutProductsCategorySlugSubcategorySlugIndexRoute
  '/_layout/products/$categorySlug/$subcategorySlug/$productSlug/': typeof LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$collection'
    | '/auth/$id'
    | '/'
    | '/order'
    | '/api/auth/$'
    | '/order-history'
    | '/products/$categorySlug'
    | '/products/$categorySlug/$subcategorySlug'
    | '/products/$categorySlug/$subcategorySlug/$productSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$collection'
    | '/auth/$id'
    | '/'
    | '/order'
    | '/api/auth/$'
    | '/order-history'
    | '/products/$categorySlug'
    | '/products/$categorySlug/$subcategorySlug'
    | '/products/$categorySlug/$subcategorySlug/$productSlug'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/$collection'
    | '/auth/$id'
    | '/_layout/'
    | '/order/'
    | '/api/auth/$'
    | '/_layout/order-history/'
    | '/_layout/products/$categorySlug/'
    | '/_layout/products/$categorySlug/$subcategorySlug/'
    | '/_layout/products/$categorySlug/$subcategorySlug/$productSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  AuthIdRoute: typeof AuthIdRoute
  OrderIndexRoute: typeof OrderIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/auth/$id': {
      id: '/auth/$id'
      path: '/auth/$id'
      fullPath: '/auth/$id'
      preLoaderRoute: typeof AuthIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/$collection': {
      id: '/_layout/$collection'
      path: '/$collection'
      fullPath: '/$collection'
      preLoaderRoute: typeof LayoutCollectionRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/order-history/': {
      id: '/_layout/order-history/'
      path: '/order-history'
      fullPath: '/order-history'
      preLoaderRoute: typeof LayoutOrderHistoryIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/products/$categorySlug/': {
      id: '/_layout/products/$categorySlug/'
      path: '/products/$categorySlug'
      fullPath: '/products/$categorySlug'
      preLoaderRoute: typeof LayoutProductsCategorySlugIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/$categorySlug/$subcategorySlug/': {
      id: '/_layout/products/$categorySlug/$subcategorySlug/'
      path: '/products/$categorySlug/$subcategorySlug'
      fullPath: '/products/$categorySlug/$subcategorySlug'
      preLoaderRoute: typeof LayoutProductsCategorySlugSubcategorySlugIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products/$categorySlug/$subcategorySlug/$productSlug/': {
      id: '/_layout/products/$categorySlug/$subcategorySlug/$productSlug/'
      path: '/products/$categorySlug/$subcategorySlug/$productSlug'
      fullPath: '/products/$categorySlug/$subcategorySlug/$productSlug'
      preLoaderRoute: typeof LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutCollectionRoute: typeof LayoutCollectionRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutOrderHistoryIndexRoute: typeof LayoutOrderHistoryIndexRoute
  LayoutProductsCategorySlugIndexRoute: typeof LayoutProductsCategorySlugIndexRoute
  LayoutProductsCategorySlugSubcategorySlugIndexRoute: typeof LayoutProductsCategorySlugSubcategorySlugIndexRoute
  LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRoute: typeof LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCollectionRoute: LayoutCollectionRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutOrderHistoryIndexRoute: LayoutOrderHistoryIndexRoute,
  LayoutProductsCategorySlugIndexRoute: LayoutProductsCategorySlugIndexRoute,
  LayoutProductsCategorySlugSubcategorySlugIndexRoute:
    LayoutProductsCategorySlugSubcategorySlugIndexRoute,
  LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRoute:
    LayoutProductsCategorySlugSubcategorySlugProductSlugIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  AuthIdRoute: AuthIdRoute,
  OrderIndexRoute: OrderIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
